EVG-7372 don't use cache for container pool settings
evergreen-ci/evergreen pull request #4041
Opened 2020-09-28 19:31 UTC by ablack12

2020-09-28 19:45 UTC, john-m-liu requested changes
The places calling validator.CheckDistro still use cached pool settings, but those aren't as big of a deal

2020-09-28 19:45 UTC, john-m-liu commented on model/distro/distro.go
> -	if s == nil {
I think you'll need to update some tests if you remove this check

2020-09-29 15:24 UTC, ablack12 commented
That was mildly intentional but I can add it there.

2020-09-29 15:58 UTC, john-m-liu approved these changes

2020-09-29 17:46 UTC, merged