EVG-13300 include PR commit queue item info
evergreen-ci/evergreen pull request #4112
Opened 2020-10-27 18:42 UTC by ablack12

![image](https://user-images.githubusercontent.com/26798134/97346860-6416a780-1862-11eb-8b5c-d9d77009c7be.png)

Not sure how y'all usually handle the two repo issue but here:
https://github.com/evergreen-ci/spruce/pull/491

2020-10-28 13:44 UTC, john-m-liu requested changes
The test failures look like minor things that are just fixed by changing the expected output

2020-10-28 13:44 UTC, john-m-liu commented on graphql/resolvers.go
> +			return nil, InternalServerError.Send(ctx, fmt.Sprintf("error finding patches: %s", err.Error()))
weird that what was here before didn't cause lint to fail 🤔

2020-10-28 13:44 UTC, john-m-liu commented on graphql/resolvers.go
> +					return nil, InternalServerError.Send(ctx, fmt.Sprintf("error finding patch: %s", err.Error()))
This might be better as a NotFound since the most common error returned by FindPatchById will probably be that

2020-10-28 13:44 UTC, john-m-liu commented on graphql/schema.graphql
> +  RemoveItemFromCommitQueue(commitQueueId: String!, issue: String!): String
I would make this camelCase to be consistent with the others

2020-10-28 14:43 UTC, malikchaya2 approved these changes
nice! :tada:

2020-10-29 14:12 UTC, john-m-liu approved these changes

2020-11-02 20:28 UTC, merged