EVG-13249 speed up finding parent display tasks
evergreen-ci/evergreen pull request #4113
Opened 2020-10-28 15:53 UTC by john-m-liu

This is only half of the ticket, the second half is a logically different change so it'll be a separate pr
- Remove the FindWithDisplayTasks function. It was problematic for two reasons - it was named in a way that said "task.Find but also includes display tasks in the results" (the regular task.Find does not), and also that the way it added display tasks to its results was inefficient
- For any callers using it as a task.FindAll, switch them to using FindAll. The fact that the function didn't actually link display tasks for a long time suggests that most callers are in this bucket. This part is probably the most bug-prone if I misread what the caller was doing
- For any callers actually using it for its intended purpose, split them into 2 calls - 1 to find tasks, and 1 to link up parent tasks. The linking part is doing a single query that has a dedicated index

2020-11-02 17:03 UTC, ablack12 requested changes

2020-11-02 19:15 UTC, john-m-liu commented on model/lifecycle.go
> +	if err != nil && !adb.ResultsNotFound(err) {
fixed

2020-11-02 19:15 UTC, john-m-liu commented on model/task/task.go
> +	tasksCopy := tasks
I didn't want to destructively modify the input. I think go doesn't do it anyway but it made me feel better

2020-11-03 16:02 UTC, ablack12 approved these changes

2020-11-03 21:13 UTC, merged