EVG-13580 Dont allow restarting of execution tasks
evergreen-ci/evergreen pull request #4309
Opened 2021-01-13 19:53 UTC by khelif96

2021-01-13 20:25 UTC, SupaJoon approved these changes

2021-01-13 21:30 UTC, john-m-liu requested changes

2021-01-13 21:30 UTC, john-m-liu commented on graphql/util.go
> +	t, err := task.FindOneId(*at.Id)
Instead of doing this, you should call at.BuildFromService. All the data is already there, it just needs to be converted

2021-01-13 21:30 UTC, john-m-liu commented on graphql/util.go
> +	displayTask, err := t.GetDisplayTask()
Instead of doing this, you can call t.IsPartOfDisplay. With both of these changes I think you also won't need to have a separate function for this

2021-01-14 15:03 UTC, john-m-liu approved these changes

2021-01-14 15:03 UTC, merged