EVG-13072 command for upstream patches to post key-value pairs
evergreen-ci/evergreen pull request #4370
Opened 2021-02-05 18:21 UTC by malikchaya2

pr changes

add command

 interactive rebase in progress; onto 20df8345a

2021-02-05 19:35 UTC, malikchaya2 commented on model/patch/patch.go
> +				bsonutil.GetDottedKeyName(TriggersKey, TriggerInfoDownstreamParametersKey): parameters,
This is temporary. I will move it into EVG-13072

2021-02-05 20:25 UTC, malikchaya2 commented on service/api_task_test.go
> +		Convey("with a set of task end details indicating that task has succeeded", func() {
I'll change this message

2021-02-09 23:20 UTC, ybrill requested changes

2021-02-12 14:27 UTC, malikchaya2 commented on agent/command/downstream_expansions_set.go
> +		err = comm.SetDownstreamParams(ctx, patchData, conf.Task.Id)
discussed over slack

2021-02-12 15:48 UTC, ybrill requested changes

2021-02-12 15:48 UTC, ybrill commented on agent/internal/client/interface.go
> +	"github.com/evergreen-ci/evergreen/model/patch"
it looks like this package is getting imported twice now: once as patch and once as patchmodel (on line 14)

2021-02-12 15:48 UTC, ybrill commented on agent/internal/client/methods.go
> +	"github.com/evergreen-ci/evergreen/model/patch"
here too: the patch package is aliased on the next line as `patchmodel`. 
I don't know why we aliased it, but we should probably just import it once either with or without the alias.

2021-02-12 15:48 UTC, ybrill commented on agent/internal/client/methods.go
> +	if len(downstreamParams) == 0 {
Maybe this check would be more appropriate in the command, to only call `comm.SetDownstreamParams` when there are params to send, as opposed to the communicator being responsible for it.
🤷‍♂️

2021-02-12 15:48 UTC, ybrill commented on apimodels/agent_models.go
> +type PatchData struct {
It looks like we're not using this anymore

2021-02-12 15:48 UTC, ybrill commented on service/api_task_test.go
> +			details := &apimodels.PatchData{
doesn't the route take a slice of patch parameters now?

2021-02-16 22:42 UTC, ybrill commented on agent/internal/client/mock.go
> +	"github.com/evergreen-ci/evergreen/model/patch"
this one too...

2021-02-16 22:42 UTC, ybrill commented on service/api.go
> +	if err != nil {
I think it would probably be best to also check if `p == nil` (although it seams unlikely).

2021-02-16 22:42 UTC, ybrill commented on service/api_task_test.go
> +func getDownstreamParamsEndpoint(t *testing.T, as *APIServer, hostId, taskId string, details *[]patch.Parameter) *httptest.ResponseRecorder {
does `details` benefit from being a pointer?

2021-02-17 14:37 UTC, malikchaya2 commented on service/api_task_test.go
> +func getDownstreamParamsEndpoint(t *testing.T, as *APIServer, hostId, taskId string, details *[]patch.Parameter) *httptest.ResponseRecorder {
no, changing

2021-02-17 15:57 UTC, ybrill commented on service/api.go
> +	if err != nil {
just following up on this one

2021-02-17 16:02 UTC, ybrill approved these changes

2021-02-17 16:42 UTC, merged