EVG-12844 Return build variant display name
evergreen-ci/evergreen pull request #4421
Opened 2021-02-22 23:11 UTC by khelif96

This field was added to two resolvers. I think in the future we should consolidated these types into one type Since they are essentially returning the same info. 

It seemed out of scope for this ticket.

2021-02-23 18:53 UTC, SupaJoon approved these changes

2021-02-23 19:26 UTC, SupaJoon requested changes
we should handle sorting and filtering task results by build variant displayName in this PR or open additional tickets

2021-02-24 22:44 UTC, khelif96 commented
Should now allow filtering by build variant display name and normal build variant name

2021-02-26 20:34 UTC, SupaJoon approved these changes

2021-03-01 15:55 UTC, merged