EVG-14716 Added AuthorDisplayName to Patch type
evergreen-ci/evergreen pull request #4741
Opened 2021-06-10 20:53 UTC by ziyielenachen

[EVG-14716](https://jira.mongodb.org/browse/EVG-14716)

### Description 
Added a new field called authorDisplayName to type Patch. This will be utilized for the PatchCard on spruce so that the project patches page displays the authors' name.

### Testing 
Added a unit test

2021-06-10 21:02 UTC, khelif96 requested changes
Great Start! Just missing something from your tests

2021-06-10 21:02 UTC, khelif96 commented on graphql/resolvers.go
> +	fmt.Printf("++++++++++++++++++++++++++++++")
left over logging

2021-06-10 21:02 UTC, khelif96 commented on graphql/tests/patch/queries/authorDisplayName.graphql
> +    author
These tests don't actually fetch the authorDisplayName field

2021-06-10 21:53 UTC, ziyielenachen commented on graphql/resolvers.go
> +	fmt.Printf("++++++++++++++++++++++++++++++")
oops sorry haha

2021-06-11 13:43 UTC, ablack12 approved these changes

2021-06-11 13:43 UTC, ablack12 commented on graphql/resolvers.go
> +		return "", ResourceNotFound.Send(ctx, fmt.Sprintf("Could not find user from user ID"))
nit: you don't need fmt.Sprintf here because you aren't including any formatting

2021-06-11 13:56 UTC, malikchaya2 approved these changes

2021-06-11 20:13 UTC, khelif96 approved these changes

2021-06-11 21:02 UTC, merged