EVG-14924: Fetch cedar test results for tasks.
evergreen-ci/evergreen pull request #4803
Opened 2021-07-01 21:23 UTC by julianedwards

JIRA: https://jira.mongodb.org/browse/EVG-14924

I updated the task struct in model to also fetch and merge cedar test results wherever we merge new test results. I also fixed the display task test results issue that was causing the original issue from this ticket and cleaned up the legacy UI. 
I tested in staging that the test results are rendered properly with their logs. Upon deploy, we should watch out for display task UI pages since we don't have those in staging.

2021-07-01 22:16 UTC, ybrill requested changes
How does the waterfall get test results from cedar?
Like, I see [Annie commented](https://github.com/evergreen-ci/evergreen/blob/777962000715c87f2844d9c7275261436d90e1d2/service/waterfall.go#L384) we don't need to call MergeNewTestResults for tasks that have results in cedar, but why not? Where are they fetched?

2021-07-01 22:16 UTC, ybrill commented on model/task/task.go
> +func (t *Task) MergeTestResults() error {
I think we need to switch to this new function [here too](https://github.com/evergreen-ci/evergreen/blob/777962000715c87f2844d9c7275261436d90e1d2/trigger/task.go#L807)

2021-07-02 14:57 UTC, ybrill approved these changes

2021-07-02 14:59 UTC, julianedwards commented
> How does the waterfall get test results from cedar?
Like, I see Annie commented we don't need to call MergeNewTestResults for tasks that have results in cedar, but why not? Where are they fetched?

I think we did this cause it was super slow to fetch all the results from the waterfall.

2021-07-02 15:21 UTC, merged