EVG-14840 Fetch latest execution task if the display task's current execution doesn't exist
evergreen-ci/evergreen pull request #4807
Opened 2021-07-06 17:36 UTC by malikchaya2

[EVG-14840](https://jira.mongodb.org/browse/EVG-14840)

### Description 
If an execution task only runs on the second execution of a display task (when it is restarted), then the execution task's execution will not be the same as the display tasks's execution. 
### Testing 
[Tested on staging](http://evergreen-staging.spruce.s3-website-us-east-1.amazonaws.com/version/60e4620197b1d32239314179/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

2021-07-06 18:29 UTC, ybrill commented
I don't understand how we reach a situation where an execution task has only a single execution. Don't [all the execution tasks get restarted at once](https://github.com/evergreen-ci/evergreen/blob/4e70303913f203ba2d5340d1cb6801f32765d5ab/model/task/task.go#L1882-L1890)?

2021-07-06 19:57 UTC, malikchaya2 commented
> I don't understand how we reach a situation where an execution task has only a single execution. Don't [all the execution tasks get restarted at once](https://github.com/evergreen-ci/evergreen/blob/4e70303913f203ba2d5340d1cb6801f32765d5ab/model/task/task.go#L1882-L1890)?
> We saw situations where there was a setup or system failure and the first run generated less execution tasks than the restart.

We've had situations where it system system failed and it generated less execution tasks than the restart did.

2021-07-06 21:00 UTC, ablack12 approved these changes
This is definitely a bandaid, since earlier executions of the display task will probably show the wrong execution. However, I think that question is rare enough that we can push it off until [EVG-14533](https://jira.mongodb.org/browse/EVG-14533)

2021-07-06 21:02 UTC, ablack12 requested changes
This issue with this ticket was also specifically restarts, wasn't it? Do we need to do anything to https://github.com/evergreen-ci/evergreen/blob/8da959940db4bf5417b3abaef599c68b0a8f1453/model/lifecycle.go#L279 or does that seem like it will work as expected? (Or were you able to verify in staging that restarts worked correctly?)

2021-07-06 21:25 UTC, malikchaya2 commented
> This issue with this ticket was also specifically restarts, wasn't it? Do we need to do anything to
> 
> https://github.com/evergreen-ci/evergreen/blob/8da959940db4bf5417b3abaef599c68b0a8f1453/model/lifecycle.go#L279
> 
> or does that seem like it will work as expected? (Or were you able to verify in staging that restarts worked correctly?)

I don't think there is anything wrong with restarts. Initially, it looked like the problem was that the display task restart didn't restart the execution tasks because the execution task link said the task wasn't found when we expected there to be one. However, the problem is really that the restarted execution task is given an execution based on how many there are in the db (0 if there are none), but looked up based on the execution of the display task (1 if if ran once before), causing it to not be found. 

In staging, I was able to restart a version which restarted the display task and the generated execution task (which didn't run in the first execution because I unscheduled it)

2021-07-07 14:19 UTC, ablack12 approved these changes

2021-07-07 14:37 UTC, merged