EVG-14958 Verify validate project configs
evergreen-ci/evergreen pull request #5024
Opened 2021-09-14 04:24 UTC by bynn

[EVG-14958](https://jira.mongodb.org/browse/EVG-14958)

### Description 
validate to use local read

### Testing 
  < add a description of how you tested it >

2021-09-15 19:48 UTC, ablack12 approved these changes

2021-09-15 19:48 UTC, ablack12 requested changes
oops sorry i button mashed that somehow

2021-09-23 06:38 UTC, bynn commented
this seems functional right now but is there a reason why i cant do this completely locally by also moving the validator commands from api.go?

2021-09-24 17:19 UTC, ablack12 approved these changes
You're right that this CLI command doesn't do anything that can't be run locally, however we have an upcoming project to improve the validator in ways that _will_ require some database lookup, which can't be done locally. That being said we may still want to refactor this eventually to send the project ref to the client side, since marshalling/unmarshalling yaml is expensive and this won't be the typical use case. cc @hadjri 

Also remember to increment  the client version string.

2021-09-24 20:01 UTC, merged