EV6-6687 Enable commit-queue delete command to not require passing a project
evergreen-ci/evergreen pull request #5273
Opened 2021-12-21 21:56 UTC by Chukwurado

[EVG-6687](https://jira.mongodb.org/browse/EVG-6687)

### Description 
Make passing a project when running `command-queue delete` not required

2021-12-22 09:05 UTC, malikchaya2 commented on rest/client/interface.go
> -	DeleteCommitQueueItem(ctx context.Context, projectID string, item string) error
This also needs to be edited in rest/client/mock.go

2021-12-22 09:06 UTC, malikchaya2 reviewed
This looks great! I would suggest testing these changes locally or on staging to make sure that it still works as expected.

2021-12-22 16:00 UTC, ablack12 requested changes
Need to increment client version string https://github.com/evergreen-ci/evergreen/blob/cc9bd2c636945353e6748be842e441e83b58a616/config.go#L35

2021-12-22 16:00 UTC, ablack12 commented on rest/client/methods.go
> +	requestedPatch, err := patch.FindOneId(item)
need to check if requestedPatch == nil

2021-12-28 22:23 UTC, hadjri approved these changes
LGTM, go ahead and merge once my 2 comments are addressed!

2021-12-28 22:23 UTC, hadjri commented on rest/client/methods.go
> +		return errors.Wrap(err, "item not found")
Since error is nil here you can just return an error with the message only.

2021-12-28 22:23 UTC, hadjri commented on config.go
> +	ClientVersion = "2021-12-22"
Need to increment one more time, unfortunately its updated again since we started review.

2022-01-05 06:00 UTC, merged