EVG-14646 Add json option to evergreen host list
evergreen-ci/evergreen pull request #5307
Opened 2022-01-12 15:42 UTC by Chukwurado

[EVG-14646](https://jira.mongodb.org/browse/EVG-14646)

### Description 
Add option to print out list of hosts in json format.

2022-01-12 15:56 UTC, ablack12 commented
@Chukwurado can you please share a screenshot of what this output looks like from staging or local testing?

2022-01-12 16:06 UTC, Chukwurado commented
> @Chukwurado can you please share a screenshot of what this output looks like from staging or local testing?

@ablack12 just added in the description above

2022-01-12 22:13 UTC, hadjri requested changes

2022-01-12 22:13 UTC, hadjri commented on operations/host_spawn.go
> +	for i, h := range hosts {
Can we try to simply marshal the host list to JSON and print it like the way we do here? https://github.com/evergreen-ci/evergreen/blob/main/operations/patch_list.go#L88 This seems cleaner than hardcoding.

2022-01-13 21:01 UTC, ablack12 commented on operations/host_spawn.go
> +		AvailabilityZone string `json:"availabilityZone"`
We use snake case by convention for json, so can these be host_name and availability_zone?

2022-01-13 21:01 UTC, ablack12 commented
Also need to increment the ClientVersion string

2022-01-14 15:03 UTC, ablack12 approved these changes

2022-01-14 19:18 UTC, hadjri approved these changes

2022-01-14 20:12 UTC, merged