EVG-6846 Return error if a task referenced in buildvariant is also referenced in taskgroup
evergreen-ci/evergreen pull request #5328
Opened 2022-01-22 02:41 UTC by hadjri

[EVG-6846](https://jira.mongodb.org/browse/EVG-6846)

### Description 
Return error if task referenced in a buildvariant is also referenced in a task group in the buildvariant

### Testing 
Updated unit tests.

2022-01-24 18:31 UTC, ablack12 requested changes

2022-01-24 18:31 UTC, ablack12 commented on validator/project_validator.go
> +// the set of project tasks and is not referenced in the task group of the buildvariant
Nit: should end sentences with periods and start with capitalized sentences (this was wrong before your change but it's hard to read)

2022-01-24 18:31 UTC, ablack12 commented on validator/project_validator.go
> +			taskGroupTaskSet[task] = true
Instead of doing map[taskName] -> true, we can do map[taskName] -> taskGroupName; that way at 598 we can print the task group name also.

2022-01-24 18:31 UTC, ablack12 commented on validator/project_validator.go
> +						Level: Error,
If current projects already rely on this behavior, we should change this to Warning level

2022-01-24 18:58 UTC, bynn approved these changes

2022-01-25 17:51 UTC, ablack12 approved these changes
LGTM with nits!

2022-01-25 17:51 UTC, ablack12 commented on units/generate_tasks_test.go
> +	{
nit: can you fix the spacing here?

2022-01-25 17:51 UTC, ablack12 commented on validator/project_validator_test.go
> +			fmt.Println("Errors: ", errs)
leftover debugging

2022-01-25 17:51 UTC, ablack12 commented on validator/project_validator_test.go
> +func TestValidateTaskGroupsInBV(t *testing.T) {
this is really well organized!

2022-01-25 22:28 UTC, hadjri commented on validator/project_validator_test.go
> +func TestValidateTaskGroupsInBV(t *testing.T) {
Thanks! :)

2022-01-25 22:57 UTC, merged