EVG-16213 Start logging graphql request stats to splunk
evergreen-ci/evergreen pull request #5372
Opened 2022-02-07 23:38 UTC by khelif96

[EVG-16213](https://jira.mongodb.org/browse/EVG-16213)

### Description 
Starts logging Graphql request stats to Splunk.
Now logs duration along side request names, variables and other metadata. 

### Testing 
![image](https://user-images.githubusercontent.com/4605522/152890273-2eba611e-4722-491a-adb8-adf015af188c.png)

2022-02-07 23:39 UTC, khelif96 commented
@bsamek tagging you irt the conversation we had about logging extra data to splunk. I can hold off on merging until Jonathans investigation is complete.

2022-02-08 15:10 UTC, bsamek commented
@khelif96 Yes, I think we should hold off until https://jira.mongodb.org/browse/EVG-16193 is closed https://jira.mongodb.org/browse/EVG-16193.

2022-02-08 20:01 UTC, julianedwards requested changes

2022-02-08 22:01 UTC, khelif96 commented on graphql/splunktracing.go
> +var _ interface {
The methods below are types for hooks that gqlgen expects. I believe it is extending the SplunkTracing interface and adding the methods gqlgen expects.

2022-02-08 22:04 UTC, julianedwards commented on graphql/splunktracing.go
> +var _ interface {
I don't think you need this then, since the struct methods already implement the graphql interfaces

2022-02-09 21:34 UTC, julianedwards requested changes

2022-02-09 21:34 UTC, julianedwards commented on graphql/splunktracing.go
> +			"message": "no operation context found",
Can you make this message more explicit, specifically that this is the operation context for a graphql request?

2022-03-07 16:48 UTC, julianedwards commented on graphql/splunktracing.go
> +type SplunkTracing struct{}
Add documentation here.

2022-03-07 17:09 UTC, julianedwards approved these changes

2022-03-07 19:03 UTC, merged