EVG-16240: Add ContainerAllocatedTime to Task document
evergreen-ci/evergreen pull request #5405
Opened 2022-02-17 02:39 UTC by hhoke

[EVG-16240](https://jira.mongodb.org/browse/EVG-16240)

### Description 
Added ContainerAllocatedTime, left ScheduledTime largely as-is and added ContainerAllocatedTime where appropriate.

### Testing 
  None

2022-02-17 16:04 UTC, Kimchelly requested changes
Going to have UI review the GraphQL schema change.

2022-02-17 16:06 UTC, Kimchelly commented on units/stats_task_end.go
> +	if !j.task.ContainerAllocatedTime.IsZero() {
If you use Unix zero time as the zero value, this will only work if you use `utility.IsZeroTime` because `IsZero` only checks for Go zero time.

2022-02-17 16:49 UTC, khelif96 approved these changes
Graphql changes LGTM. You will need to open a front end pr and run `yarn codegen` after this is merged.

2022-02-17 20:44 UTC, hhoke commented on model/lifecycle.go
> +		ContainerAllocatedTime: utility.ZeroTime,
Given that this field, like `DependenciesMetTime`, will not appear on all task documents, this makes sense.

2022-02-17 20:52 UTC, hhoke commented on service/stats.go
> +			task.ContainerAllocatedTimeKey,
I think so.

2022-02-18 15:18 UTC, Kimchelly commented on model/task/task.go
> +	// Dispatch - the time the task runner starts up the agent on the host.
I would put periods at the end of these since each line is a completed thought.

2022-02-18 15:19 UTC, Kimchelly commented on service/stats.go
> +			task.ContainerAllocatedTimeKey,
This needs to be set on the UITask, otherwise adding this field does nothing.

2022-02-22 15:38 UTC, Kimchelly approved these changes

2022-02-22 15:43 UTC, merged