EVG-16479 Update merge logic for build variants
evergreen-ci/evergreen pull request #5511
Opened 2022-03-22 22:31 UTC by bynn

[EVG-16479](https://jira.mongodb.org/browse/EVG-16479)

### Description 
allow users to add tasks to bv before defining it in one of the include files

### Testing 
unit test

2022-03-23 22:29 UTC, bynn commented on model/project_parser_merge_functions.go
>  				catcher.Errorf("build variant '%s' has been declared already", bv.Name)
done

2022-03-23 22:29 UTC, bynn commented on model/project_parser.go
> -		pbv.DisplayTasks == nil &&
we would only want to not merge the build variants if only one has the non-task declared and i made a mistake when i first wrote this of checking if display tasks were not defined as well

2022-03-25 15:16 UTC, ablack12 requested changes

2022-03-25 15:16 UTC, ablack12 commented on model/project_parser.go
> -		pbv.DisplayTasks == nil &&
So should line 385 be more like (len(pbv.Task) +len(pbv.DisplayTasks) > 0 ?

2022-03-25 15:39 UTC, bynn commented on model/project_parser.go
> -		pbv.DisplayTasks == nil &&
yeah i think that makes sense but i kept it an != 0 because i thought it was more clear.

2022-03-25 15:45 UTC, ablack12 approved these changes

2022-03-28 17:23 UTC, merged