EVG-13943: Link Legacy waterfall to project health
evergreen-ci/evergreen pull request #5576
Opened 2022-04-14 20:14 UTC by SupaJoon

[EVG-13943](https://jira.mongodb.org/browse/EVG-13943)

### Description 
![Uploading Screen Shot 2022-04-14 at 4.03.01 PM.png…]()

2022-04-14 20:28 UTC, ablack12 commented on public/static/js/menu.js
> +  console.log( $window.user, $window.NewUILink)
Is this debugging?

2022-04-14 21:46 UTC, khelif96 requested changes
Gonna Request Changes to block merging this PR. We shouldn't merge this until we are ready to launch

2022-04-15 13:38 UTC, ablack12 approved these changes
LGTM whenever we launch 🥳

2022-05-10 18:54 UTC, khelif96 approved these changes

2022-05-10 18:55 UTC, khelif96 commented
@SupaJoon  can you merge in main and make sure it still works since the pr has been stale?

2022-05-11 14:11 UTC, merged