EVG-16797 add stepback resolver and removed field
evergreen-ci/evergreen pull request #5708
Opened 2022-06-09 13:56 UTC by ablack12

[EVG-16797](https://jira.mongodb.org/browse/EVG-16797)

### Description 
Two things found while testing:
1) Added back in the restricted option to the legacy page, which was removed accidentally in https://github.com/evergreen-ci/evergreen/commit/c55a71bdcc27f5f94d485f58cdbc9483f80f172e (cc @bynn )
2) Stepback on save doesn't exist on the new UI so I added the resolver; the front end can be done in https://jira.mongodb.org/browse/EVG-17044 but should be v simple

2022-06-10 20:11 UTC, sophstad approved these changes

2022-06-10 20:37 UTC, malikchaya2 commented
I restarted the e2e tests because I think they may be flaky

2022-06-10 20:37 UTC, malikchaya2 approved these changes

2022-06-13 12:47 UTC, khelif96 requested changes

2022-06-13 13:43 UTC, merged

2022-06-13 13:45 UTC, ablack12 commented on graphql/resolvers.go
> +func (r *mutationResolver) DeactivateStepbackTasks(ctx context.Context, projectID string) (bool, error) {
Oops sorry I merged this with an old tab and your comment didn't load until i clicked merge 🤦‍♀️  Can you tell me what this means?