Evg 16009 Remove BuildNumber and global build number tracking
evergreen-ci/evergreen pull request #5711
Opened 2022-06-10 19:10 UTC by ZackarySantana

[EVG-16009](https://jira.mongodb.org/browse/EVG-16009)

### Description 
BuildNumber was used to populate a legacy REST v1 route that the new API does not use. It has been removed from the REST v1 route, and should be removed from our models and DB build model.

Remove the global folder and buildnumber.

### Testing 
Removed tests and ran evergreen patch with affected tests

2022-06-13 22:24 UTC, bynn approved these changes

2022-06-14 14:40 UTC, ablack12 requested changes

2022-06-14 14:40 UTC, ablack12 commented on cmd/generate-lint/generate-lint.go
> +	diffCmd := exec.Command("git", "diff", strings.TrimSpace(string(base)), "--name-only", "--diff-filter=d")
what is this change for?

2022-06-14 14:42 UTC, ablack12 approved these changes

2022-06-14 14:42 UTC, ablack12 commented on cmd/generate-lint/generate-lint.go
> +	diffCmd := exec.Command("git", "diff", strings.TrimSpace(string(base)), "--name-only", "--diff-filter=d")
jk did a google, good find

2022-06-14 19:56 UTC, merged