EVG-16886 Split raw test logs by line breaks
evergreen-ci/evergreen pull request #5902
Opened 2022-08-29 16:59 UTC by hadjri

[EVG-16886](https://jira.mongodb.org/browse/EVG-16886)

### Description 
Currently multi-line log files are uploaded on a single line in the attach.results command.  This causes the HTML log page to highlight the entire document as the "first line". Change has been made to split these logs accordingly.
### Testing 
Deployed to staging and ran attach.results on the sandbox project with two sample raw logs, one delimited by `\n` line breaks and one delimited by `\r\n` line breaks and checked that both html log pages were divided by line appropriately.

2022-08-29 17:01 UTC, khelif96 commented
Can you also check this on legacy lobster?

2022-08-29 19:37 UTC, malikchaya2 requested changes
Approved after Mohamed's comment is addressed :)

2022-08-29 19:37 UTC, malikchaya2 approved these changes

2022-08-31 17:04 UTC, khelif96 approved these changes

2022-08-31 17:30 UTC, merged