EVG-17486: Add volume migration resolver
evergreen-ci/evergreen pull request #5986
Opened 2022-10-04 17:43 UTC by sophstad

[EVG-17486](https://jira.mongodb.org/browse/EVG-17486)

2022-10-06 14:27 UTC, malikchaya2 requested changes

2022-10-06 14:27 UTC, malikchaya2 commented on graphql/mutation_resolver.go
> +		return false, err
should we wrap this error?

2022-10-11 19:53 UTC, sophstad commented on rest/data/volume.go
> +
Created a utility function for both of them to use!

2022-10-11 19:54 UTC, sophstad commented on graphql/mutation_resolver.go
> +		return false, err
I think the `getHostRequestOptions` provides sufficient context for each error; it's just a utility to wrap some repeated code so brevity seems preferable.

2022-10-12 13:54 UTC, malikchaya2 approved these changes

2022-10-12 14:05 UTC, merged