EVG-17497 Reset priority when activating task
evergreen-ci/evergreen pull request #6057
Opened 2022-11-09 20:16 UTC by hadjri

[EVG-17497](https://jira.mongodb.org/browse/EVG-17497)

### Description 
< add description, context, thought process, etc >

### Testing 
Updated unit test and deployed to staging to confirm that manually scheduling a disabled task in the UI resets its priority and lets the task actually get scheduled.

2022-11-11 16:46 UTC, hadjri commented
![image](https://user-images.githubusercontent.com/19805673/201388926-c73fff84-6cc5-4ee9-aaf2-4a6b68a299de.png)

2022-11-11 20:44 UTC, ablack12 requested changes

2022-11-11 20:44 UTC, ablack12 commented on model/task/task.go
> +				PriorityKey: evergreen.DefaultPriority,
Instead of this we can just use "$unset": which will put it back to 0

2022-11-11 20:44 UTC, ablack12 commented on model/task/task.go
> +func enableDisabledTasks(taskIDs []string) error {
Can we call this in activateTasks itself (and also move to db.go?)

2022-11-14 14:47 UTC, ablack12 approved these changes
LGTM with nits

2022-11-15 14:12 UTC, merged