EVG-17384: Expose Warnings and Errors field for versions
evergreen-ci/evergreen pull request #6300
Opened 2023-02-28 19:17 UTC by minnakt

EVG-17384

### Description
This PR exposes the warnings and errors field for versions. I added the `Warnings` into `BuildFromService` because the `Errors` were already there, but if that seems wrong I can make another resolver.

I also made some changes to the local data so that we have testing data for the UI.

### Testing
- Added GraphQL test

#### Does this need documentation?
- Yes, even if the `Warnings` field doesn't end up getting added to `BuildFromService`. The [REST V2 version documentation](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#version) seems to be missing fields like `aborted`, `order`, and `errors`.

2023-02-28 20:43 UTC, khelif96 approved these changes

2023-03-01 14:40 UTC, ablack12 requested changes
Warnings can potentially be really long; I'm not sure we want to expose these with our rest route.

2023-03-01 16:17 UTC, minnakt commented
> Warnings can potentially be really long; I'm not sure we want to expose these with our rest route.

I moved `Warnings` to a resolver so it won't show in the rest route anymore

2023-03-01 19:13 UTC, ablack12 approved these changes

2023-03-01 23:34 UTC, merged