EVG-19012: Pod.events gql field
evergreen-ci/evergreen pull request #6330
Opened 2023-03-15 18:44 UTC by SupaJoon

[EVG-19012](https://jira.mongdb.com/browse/EVG-19012)

### Description
The events field will be queried to display container events for the Containers UI

2023-03-15 20:35 UTC, Kimchelly requested changes

2023-03-15 20:35 UTC, Kimchelly commented on graphql/pod_resolver.go
> +	// populate eventlogs pointer arrays
Do we need this comment? It seems somewhat self-evident that the for loop is building a slice.

2023-03-15 20:35 UTC, Kimchelly commented on graphql/pod_resolver.go
> +	events, count, err := event.MostRecentPaginatedPodEvents(utility.FromStringPtr(obj.ID), *limit, *page)
Can `limit` or `page` ever be nil, or will GraphQL always ensure they're a non-nil value?

2023-03-16 15:01 UTC, khelif96 approved these changes

2023-03-16 19:07 UTC, Kimchelly approved these changes
LGTM mod follow-up comment.

2023-03-16 19:07 UTC, Kimchelly commented on graphql/pod_resolver.go
> +	// populate eventlogs pointer arrays
Seems like if this comment doesn't add anything, we should remove it.

2023-03-17 16:05 UTC, merged