EVG-19878, EVG-19880: Add backend validation for Parsley filters
evergreen-ci/evergreen pull request #6544
Opened 2023-05-24 16:17 UTC by minnakt

EVG-19878, EVG-19880

### Description
This PR adds backend validation for Parsley filters when saving them via GraphQL or the project [`PATCH`](https://docs.devprod.prod.corp.mongodb.com/evergreen/API/REST-V2-Usage#modify-a-project) rest route.

### Testing
- Added tests for rest route validation in `rest/route/project_test.go`
- Added tests for GraphQL validation for underlying function in `rest/data/project_settings_test.go`
- Manual testing via `/graphql` and project PATCH endpoint

2023-05-24 17:42 UTC, hadjri requested changes

2023-05-24 17:42 UTC, hadjri commented on model/project_ref.go
> +			break
Can we continue rather than break in order to get all of the duplicates instead of exiting at the first duplicate we find?

2023-05-24 18:56 UTC, hadjri approved these changes

2023-05-24 19:01 UTC, ablack12 requested changes

2023-05-24 19:01 UTC, ablack12 commented on model/project_ref.go
> +func (p ParsleyFilter) Validate() error {
this can be private if it's only called above

2023-05-24 19:01 UTC, ablack12 commented on rest/data/project_settings.go
> +		catcher.Add(err)
Since you aren't looping, there's not actually a reason to use the catcher here, you can just do a regular error check

2023-05-24 20:44 UTC, sophstad approved these changes

2023-05-25 14:31 UTC, ablack12 approved these changes

2023-05-25 14:31 UTC, ablack12 commented on rest/route/project.go
> +	// validate Parsley filters before updating project
nit: should capitalize validate here for a proper sentence (https://docs.google.com/document/d/1-DB1FQ_zb5fX_0pnVcwyU0HmJPrloFBu6qSE8dkk8PU/edit#)

2023-05-25 19:02 UTC, merged