EVG 20071 listen for event
evergreen-ci/evergreen pull request #6583
Opened 2023-06-05 15:07 UTC by bsamek

- EVG-20070 Add GitHub merge queue ADR
- Listen for MergeGroupEvent

2023-06-05 15:08 UTC, bsamek commented
Note that the ADR is in a separate PR, https://github.com/evergreen-ci/evergreen/pull/6581, but I included it here for context, since it isn't merged yet. The same reviewer for that PR should review this one @ablack12 .

2023-06-05 22:27 UTC, malikchaya2 requested changes

2023-06-05 22:27 UTC, malikchaya2 commented on rest/route/github.go
> +	case *github.MergeGroupEvent:
Is this meant to be temporary? If yes, can we please add a ticket number or comment indicating what it's doing and a todo to remove it?

2023-06-05 22:27 UTC, malikchaya2 commented on docs/decisions/2023-06-05_github_merge_queue.md
> +# 2023-06-05 GitHub Merge Queue
Will this be removed before merging and merged in [6581](https://github.com/evergreen-ci/evergreen/pull/6581/files) instead?

2023-06-06 13:53 UTC, malikchaya2 commented on docs/decisions/2023-06-05_github_merge_queue.md
> +# 2023-06-05 GitHub Merge Queue
thank you!

2023-06-06 13:56 UTC, malikchaya2 commented on rest/route/github.go
> +	case *github.MergeGroupEvent:
In that case, I would suggest adding a comment similar to [this format](https://github.com/malikchaya2/evergreen/blob/46deb4bceb4c3d745bc6250a60d04867851c08ed/rest/route/project.go#L477-L479).

2023-06-06 15:54 UTC, merged