EVG-20073 Create versions for GitHub merge queue
evergreen-ci/evergreen pull request #6658
Opened 2023-06-14 16:00 UTC by bsamek

EVG-20073

### Description

This adds support to the patch-intent-processor amboy job for GitHub merge queue
items.

### Testing

This tests the new requester type by running similar integration tests for the
patch-intent-processor job as currently exist for other requester types.

### Documentation

Light edits to the ADR. There are not user-facing changes yet, so I have not
added public docs.

2023-06-15 17:36 UTC, malikchaya2 commented on model/patch/github_merge.go
>  		return nil, errors.New("head ref cannot be empty")
Should this say head `sha`?

2023-06-15 17:49 UTC, malikchaya2 requested changes

2023-06-15 18:22 UTC, bsamek commented on model/patch/github_merge.go
> +	headBranch := strings.Join([]string{split[2], baseBranch, split[len(split)-1]}, "/")
done

2023-06-15 18:22 UTC, bsamek commented on model/patch/patch.go
> +	return p.Alias == evergreen.CommitQueueAlias || p.IsPRMergePatch() || p.GithubMergeData.HeadSHA != ""
done

2023-06-15 18:22 UTC, bsamek commented on units/patch_intent.go
> +		u = &user.DBUser{
I think it's better for this to be in code than just in the database. If it's only in the database, then we could try to start another Evergreen (for example, a staging environment), and it won't start until someone figures out what the error message means. I'm also following the convention in the function just above this one, for the GitHub PR user.

2023-06-16 14:34 UTC, malikchaya2 commented on units/patch_intent.go
> +		u = &user.DBUser{
good point, thanks!

2023-06-16 14:34 UTC, malikchaya2 approved these changes

2023-06-16 17:43 UTC, merged