EVG-19918 fetch config all together
evergreen-ci/evergreen pull request #6804
Opened 2023-07-20 19:29 UTC by ybrill

[EVG-19918](https://jira.mongodb.org/browse/EVG-19918)

### Description
We observed in the idle-host-termination job that each time we loaded the config it made ~30 round trips to the db and that caused the job to slow down. Although we aren't calling GetConfig there any more post #6790, getting them all in a single round trip to the db should make other calls to GetConfig much faster.

### Testing
This should be covered by the existing tests on GetConfig(), (i.e. everything in [the Admin suite](https://github.com/evergreen-ci/evergreen/blob/95c940e0db513c01e58f2ca106591dc289d2522c/config_test.go#L119))

2023-07-21 18:52 UTC, ybrill commented
evergreen retry

2023-07-25 16:08 UTC, julianedwards requested changes

2023-07-25 16:10 UTC, julianedwards commented on config.go
> -		if err := section.Get(ctx); err != nil {
Ignore this comment, I see that sections are fetched individually so this needs to exist.

2023-07-25 16:17 UTC, julianedwards commented on config_db.go
> +	for cur.Next(ctx) {
Ah I see, yeah you can't just fetch all the raw documents at once.

2023-07-25 17:06 UTC, ybrill commented on config_registry.go
> +	return errors.Wrapf(bson.Unmarshal(rawSection, section), "unmarshaling section '%s'", idString)
done

2023-07-25 17:06 UTC, ybrill commented on config_registry.go
>  var ConfigRegistry *ConfigSectionRegistry
Removed the config sections from global state.

2023-07-25 17:11 UTC, julianedwards approved these changes

2023-07-25 19:51 UTC, merged