EVG-20295 Add option to unschedule downstream triggered versions
evergreen-ci/evergreen pull request #6864
Opened 2023-08-04 16:23 UTC by hadjri

EVG-20295

### Description
Proposal #1 from the ticket isn't easily viable since cron does not ignore `activate: false`, whereas project triggers do ignore it, which is the opposite of our requested behavior. After some thinking I decided the simplest solution would be to introduce a boolean option on project triggers, where if it is set, will create deactivated versions rather than activated ones. Since false is the base case this shouldn't affect any existing workflows. Will create UI ticket on approval.

### Testing
Tested in staging, manually set the field on a trigger in the DB, triggered a version and confirmed it was [deactivated](https://spruce-staging.corp.mongodb.com/version/annie_copy2_8be2548818e8858aae06ae82e873ac1985004248_284a2ebc84b73f5ba2d3ad5c36aa78c7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). Updated existing unit tests confirming all versions/builds/tasks get deactivated when `UnscheduleTasks` is set.
### Documentation
Updated the triggers section describing this new option.

2023-08-09 14:16 UTC, malikchaya2 requested changes
I agree with this approach. While it is very specific to this use case, I think it's still the simplest way of accomplishing it in a way that is still generic enough.

2023-08-10 20:25 UTC, hadjri commented on model/project_ref.go
> +	UnscheduleTasks bool   `bson:"unschedule_tasks,omitempty" json:"unschedule_tasks,omitempty"`
Sure, changed

2023-08-11 14:50 UTC, malikchaya2 approved these changes
LGTM once tests pass

2023-08-11 16:48 UTC, hadjri commented
Created: https://jira.mongodb.org/browse/EVG-20650

2023-08-11 16:55 UTC, merged