EVG-20287 Remove unnecessary conflict check in next task
evergreen-ci/evergreen pull request #6929
Opened 2023-08-21 15:40 UTC by malikchaya2

EVG-20287
### Description
The check is unnecessary as it will never be hit. It cannot receive a task conflict from next task. It could receive a host conflict, but it seems like that specific failure is never returned back to the agent from GetNextTask anyways. Therefore, that error block never runs.

2023-08-21 22:44 UTC, hadjri requested changes
Looks like we can remove [this](https://gist.github.com/hadjri/abb921aae2f42202ac6098337f748b40#file-request-go-L27) and [this](https://gist.github.com/hadjri/00df27e209daae01b0fcf29b0e0b4ecd#file-base_client-go-L322) as well since they're unused now

2023-08-22 13:41 UTC, malikchaya2 commented
> Looks like we can remove [this](https://gist.github.com/hadjri/abb921aae2f42202ac6098337f748b40#file-request-go-L27) and [this](https://gist.github.com/hadjri/00df27e209daae01b0fcf29b0e0b4ecd#file-base_client-go-L322) as well since they're unused now

TaskConflict is still used by doHeartbeat in background.go. 
I removed HTTPConflictError.

2023-08-22 16:12 UTC, hadjri approved these changes

2023-08-24 15:41 UTC, Kimchelly reviewed
Malik is actually right, and `TaskConflict` is never set anywhere, so it can also be deleted.

2023-08-24 15:50 UTC, merged