EVG-20052
evergreen-ci/evergreen pull request #6978
Opened 2023-08-31 17:53 UTC by ZackarySantana

EVG-20052

### Description
add description, context, thought process, etc

### Testing
add a description of how you tested it

### Documentation
remember to add or edit docs in the docs/ directory if relevant

2023-08-31 18:53 UTC, ZackarySantana commented on model/event/task_event.go
> +func LogTaskPriority(taskId string, execution int, userId string, priority int64) {
Renamed to keep consistency with other methods in the same file.

2023-09-01 17:45 UTC, hadjri commented
Note: PRs need a descriptive title along with the JIRA ticket number ([example](https://github.com/evergreen-ci/evergreen/pull/6981))

2023-09-01 17:56 UTC, hadjri requested changes

2023-09-01 17:56 UTC, hadjri commented on model/lifecycle.go
> +	tasks, err := task.FindAll(db.Query(query))
Since this logic is duplicated in two places can we move it into a helper function?

2023-09-01 17:56 UTC, hadjri commented on model/lifecycle.go
> +	// Deactivate tasks with negative priority
Can we change this comment (and the other one that is identical) back to something closer to the original comment, like `Tasks with negative priority should never run, so we unschedule them`

2023-09-01 19:09 UTC, ZackarySantana commented
I attached a working video of the event logs getting updated and added a title!

2023-09-01 19:21 UTC, hadjri commented
Nit: The PR title should be describing what was actually done in the code, instead of copying the JIRA ticket tile. Something good here would be like "Add priority event logs when setting version priority"

2023-09-01 19:50 UTC, ablack12 commented
FYI I think [the new hire introduction section](https://docs.google.com/document/d/1LJHPjLb_bUZxv-l_9Y61kitzAg7u-13I5DjOhZ-deBA/edit) on how to choose a PR title is outdated (the ticket title is not always a good PR title, per Malik's advice); I'll update

2023-09-01 20:12 UTC, ZackarySantana commented
That makes sense! I updated it to align with the code changes rather than the JIRA ticket

2023-09-05 05:13 UTC, hadjri requested changes

2023-09-05 05:13 UTC, hadjri commented on model/lifecycle.go
> +func setTasksPriority(ctx context.Context, query primitive.M, priority int64, caller string) error {
We instead use `bson.M` rather than `primitive`, for consistency

2023-09-05 16:11 UTC, hadjri approved these changes

2023-09-05 18:00 UTC, merged