EVG-19921: Introduce PatchesInput.includeHidden
evergreen-ci/evergreen pull request #7116
Opened 2023-10-06 21:07 UTC by SupaJoon

EVG-19921

### Description
When `onlyHidden` is true then only hidden patches will be returned. If onlyHidden is not provided or false, then only non-hidden patches will be returned.

2023-10-18 15:52 UTC, hadjri commented on model/patch/db.go
> +	if opts.IncludeHidden != nil && !utility.FromBoolPtr(opts.IncludeHidden) {
You can just do `if !utility.FromBoolPtr(opts.IncludeHidden)`

2023-10-18 19:56 UTC, sophstad reviewed
Could you update the PR title?

2023-10-18 19:56 UTC, sophstad commented on graphql/tests/user/queries/patches-include-hidden.graphql
> +    includeHidden: patches(patchesInput: { includeHidden: true }) {
Smart test configuration!

2023-10-19 16:44 UTC, sophstad approved these changes

2023-10-20 20:58 UTC, hadjri approved these changes
approved w nit

2023-10-20 20:58 UTC, hadjri commented on model/patch/db.go
> +	if opts.IncludeHidden != nil && !utility.FromBoolPtr(opts.IncludeHidden) {
Ah - in that case you can just use [FromBoolTPtr](https://gist.github.com/hadjri/170a0435ad2d815ceff8426b63f8238d#file-optional-go-L35-L43)

2023-10-31 21:47 UTC, khelif96 commented on graphql/schema/types/patch.graphql
> +  includeHidden: Boolean
```suggestion
  includeHidden: Boolean = false
```

2023-10-31 21:48 UTC, khelif96 requested changes
Making the below suggestion will allow this change to be fully backwards compatible without breaking existing functionality.

2023-11-01 15:54 UTC, khelif96 commented on graphql/schema/types/patch.graphql
> +  includeHidden: Boolean = false
I think you need to run gqlgen again.

2023-11-02 19:41 UTC, khelif96 approved these changes

2023-11-02 19:47 UTC, merged