DEVPROD-754: Add flag for deprecating legacy distro page
evergreen-ci/evergreen pull request #7324
Opened 2023-12-15 21:36 UTC by minnakt

DEVPROD-754

### Description
Adds a flag for auto-redirecting to the new distro page. The flag will not be turned on until some time in January and I will also need to put up a banner.

<img width="532" alt="Screenshot 2023-12-15 at 4 27 49 PM" src="https://github.com/evergreen-ci/evergreen/assets/47064971/c6502aaa-2295-4230-b924-e40502c45a93">
<br /><br />

I also added a "Open Page in the New UI" button on the distros page to encourage the transition during this time. I wanted to link to a particular distro from this button, but I can't see how it's possible, since the distro appears to be stored further down in [`distros.js`](https://github.com/evergreen-ci/evergreen/blob/8502d900cd876ea877e7cc41434b2257f2fe5e71/public/static/js/distros.js#L109-L133).

### Testing
- On staging

2023-12-18 16:57 UTC, hadjri requested changes

2023-12-18 16:57 UTC, hadjri commented on service/distros.go
> +		gimlet.WriteResponse(w, gimlet.MakeJSONInternalErrorResponder(errors.Wrap(err, "retrieving admin settings")))
We'll need to return after this line

2023-12-18 16:57 UTC, hadjri commented on service/distros.go
> +		http.Redirect(w, r, newUIProjectsLink, http.StatusPermanentRedirect)
also need to return after this line

2023-12-18 16:57 UTC, hadjri commented on service/distros.go
> +		newUIProjectsLink := fmt.Sprintf("%s/distros", uis.Settings.Ui.UIv2Url)
We can remove this line and move `spruceLink` on L89 right before this block to prevent initializing the same value twice

2023-12-18 19:03 UTC, minnakt commented on service/distros.go
> +		gimlet.WriteResponse(w, gimlet.MakeJSONInternalErrorResponder(errors.Wrap(err, "retrieving admin settings")))
oops thank you!

2023-12-18 20:01 UTC, hadjri approved these changes

2023-12-20 16:35 UTC, minnakt commented
Note: I notice that Chrome seems to be caching the pages, leading to the changes from admin page not being registered sometimes. When that happens, I enable "Disable cache" in the Network tab and refresh the page with the console still open. (The console must be left open because the "Disable cache" setting is only active if it's open.) This will invalidate the cache and register the changes.

<img width="354" alt="Screenshot 2023-12-20 at 11 20 33 AM" src="https://github.com/evergreen-ci/evergreen/assets/47064971/b708446b-2a36-4c9e-b6ca-171dc64ecb6d">

You can also open an incognito tab and that should also correctly reflect the changes.

2023-12-20 18:13 UTC, merged