DEVPROD-746 Delete unused bvtu level exec timeout
evergreen-ci/evergreen pull request #7438
Opened 2024-01-22 20:36 UTC by bynn

DEVPROD-746

### Description
it was never being used and just being passed around so it is being deleted

### Testing
current tests pass

2024-01-24 15:33 UTC, Kimchelly requested changes
The code change itself LGTM, just docs questions:
* It looks like the docs still use a bvtu-level exec timeout as [its example configuration](https://github.com/evergreen-ci/evergreen/blob/76e5398afd3db461ce8da972c3ac12502df1d700/docs/Project-Configuration/Project-Configuration-Files.md?plain=1#L227). Can we move the example field somewhere else, like the task definition or something?
* In the docs above, I noticed the field is never documented where you can set it (at the top level or in a task definition), and the other fields have a short description of what they do. Can we document it now or alternatively, make a separate ticket to document `exec_timeout_secs`?

2024-01-25 16:31 UTC, bynn commented
TIcket created for documentation + adding example: https://jira.mongodb.org/browse/DEVPROD-4063 (which was maybe more work than just writing the doc haha)

2024-01-25 16:31 UTC, bynn commented
deleted the example in bvtu though

2024-01-25 16:38 UTC, Kimchelly approved these changes

2024-01-25 18:09 UTC, merged