DEVPROD-755 Add comments and refactor task logic relating to blocked tasks
evergreen-ci/evergreen pull request #7471
Opened 2024-01-31 16:19 UTC by ZackarySantana

DEVPROD-755

### Description
The ticket was created to address a couple things:
1. If there are duplicate db queries
2. Add comments/documentation
3. Mark the task as not finished if there is trouble updating its dependencies

#### Solutions
1. (This all relates to the PR linked in the ticket specifically) I scrummed through the code and didn't find any duplicate calls. There could be duplicate calls for the container task queue because the only container tasks in the queue are already vetted to have their dependencies satisfied-- but after asking Kim for some context about it, she mentioned containers are in maintenance mode and it might be too extra optimizing it as such.

2. I added some comments and documentation, I also refactored some names to make it more self-documenting. I as well added some tests to prevent regression and make sure we are using the cache.

3. I'm not sure how this behavior should exactly look. It stems from [this comment](https://github.com/evergreen-ci/evergreen/pull/6900#discussion_r1320279512) on the previous work's PR. I simply added an error check that sees if getting or updating the blocked finished tasks errored, and if it did, mark the current task as not finished.

### Testing
CI testing

2024-02-06 15:00 UTC, hadjri requested changes

2024-02-06 15:00 UTC, hadjri commented on units/check_blocked_tasks.go
> +		for _, blockingTask := range finishedBlockingTasks {
Re this [comment](https://github.com/evergreen-ci/evergreen/pull/6900#discussion_r1320279512): should we include an extra `MarkDependenciesFinished` call here to updates all direct dependencies on this task to cache whether or not this task has finished running

2024-02-06 15:46 UTC, ZackarySantana commented on model/task_lifecycle.go
> +	buildIDs := []string{}
I'll switch it back over and document that it's to ensure no duplicates!

2024-02-08 18:53 UTC, ZackarySantana commented
Im perfecting the query now- can't seem to get it down perfect but all the other logic should be stable to review- sorry about that!

2024-02-09 21:17 UTC, hadjri requested changes

2024-02-09 21:17 UTC, hadjri commented on model/task/db.go
> +func PotentiallyBlockedTasksByIds(taskIds []string) bson.M {
Doc exported function

2024-02-09 21:17 UTC, hadjri commented on model/task/db_test.go
> +// use asserts and requires
We can remove this comment

2024-02-09 21:17 UTC, hadjri commented on units/check_blocked_tasks.go
> +	// if len(t.DependsOn) == 0 || t.OverrideDependencies || !utility.IsZeroTime(t.DependenciesMetTime) {
Is this meant to be uncommented or removed?

2024-02-09 21:17 UTC, hadjri commented on model/task/task.go
> +func populateDependencyTaskCacheSingular(depCache map[string]Task, depId string) (*Task, error) {
Can we comment this because its purpose might not be clear at first glance

2024-02-09 21:17 UTC, hadjri commented on model/task/db.go
> +			{OverrideDependenciesKey: false},
OverrideDependenciesKey not existing would also be valid

2024-02-13 18:49 UTC, hadjri approved these changes

2024-02-16 15:17 UTC, merged