DEVPROD-4466 Delete lobster code from Evergreen codebase
evergreen-ci/evergreen pull request #7496
Opened 2024-02-05 20:56 UTC by khelif96

DEVPROD-4466 
DO NOT MERGE UNTIL 02/09

### Description
This pr removes access to lobster via Evergreen. It still keeps some code that handles redirecting logkeeper links to Parsley.

2024-02-06 13:08 UTC, sophstad requested changes

2024-02-06 13:08 UTC, sophstad commented on model/testresult/testresult.go
> -	case evergreen.LogViewerLobster:
I believe you can delete this variable from `globals.go`

2024-02-06 21:29 UTC, hadjri commented on model/testresult/testresult.go
> -			for _, url := range deprecatedLobsterURLs {
`deprecatedLobsterURLs` is still used elsewhere in this file can we remove it?

2024-02-08 18:51 UTC, sophstad approved these changes
👋🦞☠️

2024-02-08 21:20 UTC, merged