DEVPROD-5289: Add ParsleySettings field to DBUser struct
evergreen-ci/evergreen pull request #7625
Opened 2024-03-08 17:57 UTC by minnakt

DEVPROD-5289

### Description
(Sorry PR is not actually that big, 458 added lines were generated.)

This PR adds a new `ParsleySettings` field to the `DBUser` struct. In the future, `ParsleySettings` will hold more fields relating to user's preferences when viewing logs.

I added the `ParsleySettings.SectionsEnabled` field which describes if users should see sections in Parsley for Evergreen task logs. It should be enabled by default to expose users to the new feature.

### Testing
- Added GraphQL tests
- Added unit tests

2024-03-11 18:08 UTC, hadjri requested changes

2024-03-11 18:08 UTC, hadjri commented on rest/model/parsley.go
> +	// Whether to render task logs with sections.
Nit: start comment with the name of the field

2024-03-11 18:08 UTC, hadjri commented on rest/model/parsley.go
> +	// Regex to match in Parsley.
Same comment here

2024-03-11 18:08 UTC, hadjri commented on model/user/user_test.go
> +	assert.NotNil(t, dbUser)
This should be require.NotNil

2024-03-12 03:44 UTC, minnakt commented
Just to add on to what @SupaJoon said, another factor worth mentioning is debuggability. If we were able to look up a user's specific Parsley settings, we could have troubleshooted [EVG-19872](https://jira.mongodb.org/browse/EVG-19872) and [DEVPROD-5058](https://jira.mongodb.org/browse/DEVPROD-5058) without the need of asking the user directly in each case. I think that New Relic might not be quite sufficient for that.

2024-03-12 14:31 UTC, khelif96 commented
That all sounds great to me @SupaJoon  @minnakt! Thank you for walking me through your reasoning and for the explanation!

2024-03-14 14:38 UTC, minnakt commented on model/user/user_test.go
> +	assert.NotNil(t, dbUser)
ty!

2024-03-14 14:39 UTC, minnakt commented on graphql/schema/types/user.graphql
> +  parsleySettings: ParsleySettings
good point, done!

2024-03-18 14:30 UTC, hadjri approved these changes

2024-03-18 19:09 UTC, minnakt commented
merging — failing project settings test should be unrelated 🤔

2024-03-18 19:10 UTC, merged