DEVPROD-4768: prioritize non-task hosts for cloud status job
evergreen-ci/evergreen pull request #7629
Opened 2024-03-08 21:07 UTC by Kimchelly

DEVPROD-4768

### Description
Follow-up to #7597 - the previous change does make the job faster. Unfortunately, there's still an issue where the job only checks the first N hosts, sorted by oldest to newest creation time. If a lot of hosts were started recently _and_ they're taking a long time to actually boot up, the job will not be able to check hosts that were started later on, which can starve out later hosts that managed to start up quickly. This doesn't cause an issue for task hosts, because they can still run tasks even if they're stuck in "starting". However, host.create and spawn hosts need to go from "starting" to "running" ASAP or else the user can't get the DNS name for their host. To work around this (and given the fact that the number of host.create/spawn hosts starting up is usually small), I changed the sorting so that:

* Spawn hosts and host.create hosts always get checked first, followed by task hosts.
* Spawn hosts and host.create hosts have a check limit that's separate from task hosts. So if the check limit is 100, Evergreen can check at most 100 spawn/host.create hosts, and 100 task hosts.

### Testing
* Updated unit tests.
* Tested in staging to verify that the host status job still works.

### Documentation
N/A

2024-03-11 19:45 UTC, hadjri requested changes

2024-03-11 19:45 UTC, hadjri commented on model/host/db.go
> +func FindStartingHostsByClient(ctx context.Context, limit int) ([]HostsByClient, error) {
Can we make 500 a default const at the top of this file?

2024-03-11 19:45 UTC, hadjri commented on model/host/db.go
> +// FindStartingHostsByClient returns a map of cloud provider client options to hosts
This function now returns a list so we'll need to update this comment

2024-03-11 19:45 UTC, hadjri commented on model/host/db.go
> +	hostsByClient := []HostsByClient{}
I think these 3 lines can be replaced with `hostsByClient := append(nonTaskHosts, taskHostsByClient...)`

2024-03-11 19:46 UTC, hadjri commented
> Spawn hosts and host.create hosts always get checked first, followed by task hosts.
Is this still worth highlighting if there are now separate limits in place?

2024-03-11 20:04 UTC, Kimchelly reviewed
Our specific internal algorithms aren't really something general users need to know since it doesn't change the behavior of host.list/host.create, only the performance of them. I think the general understanding is that host.create/host.list should be as fast as we can reasonably make them, and I don't really think users otherwise care what machinery Evergreen has to achieve that.

2024-03-12 14:19 UTC, hadjri approved these changes

2024-03-12 15:36 UTC, merged