DEVPROD-7641: Create getImageDiff function to query Runtime Environments API
evergreen-ci/evergreen pull request #8066
Opened 2024-07-03 19:30 UTC by sophiabarness

DEVPROD-7641

### Description
Added getImageDiff function to query Runtime Environments API to retrieve package/toolchain changes given two AMIs. 

### Testing
Added TestGetImageDiff function to test functionality.

2024-07-08 18:53 UTC, minnakt requested changes

2024-07-08 18:53 UTC, minnakt commented on thirdparty/runtime_environments.go
> +	AMI2  string
Maybe they can have names like `AfterAMI` and `BeforeAMI` (since I think the order matters)

2024-07-08 18:53 UTC, minnakt commented on thirdparty/runtime_environments.go
> +	Limit int
I think we discussed not supporting pagination for this route just because of the filtering at the end of the function

2024-07-08 18:53 UTC, minnakt commented on thirdparty/runtime_environments_test.go
> +	opts1 := ImageDiffOptions{
Like before, overwrite `opts` instead :
```suggestion
	opts := ImageDiffOptions{
```

2024-07-08 18:53 UTC, minnakt commented on thirdparty/runtime_environments_test.go
> +	result1, err := c.getImageDiff(ctx, opts1)
Like before, overwrite `result` instead
```suggestion
	result, err := c.getImageDiff(ctx, opts)
```

2024-07-08 18:53 UTC, minnakt commented on thirdparty/runtime_environments_test.go
> +func TestGetImageDiff(t *testing.T) {
nit. add comments for each test case

2024-07-08 18:53 UTC, minnakt commented on thirdparty/runtime_environments_test.go
> +	}
can add a test case for diffing an AMI against itself

2024-07-09 00:50 UTC, minnakt commented on thirdparty/runtime_environments.go
> +	params.Set("limit", "100")
was this left over by accident? :o

2024-07-09 00:50 UTC, minnakt commented on thirdparty/runtime_environments.go
> +// ImageDiffOptions represents the arguments for getImageDiff. AMI is the starting AMI, and AMI2 is the ending AMI.
nit. update comment

2024-07-09 00:50 UTC, minnakt commented on thirdparty/runtime_environments_test.go
> +	// Verify that getImageDiff correctly returns Toolchain changes
nit. end comments with punctuation (applies to other comments here as well)

2024-07-09 00:50 UTC, minnakt commented on thirdparty/runtime_environments_test.go
> +		assert.Equal(change.Type, "Toolchains")
You can probably just have one test that has both Packages & Toolchains changes and do something like
```
	assert.True(change.Type == "Toolchains" || change.Type == "Packages")
```

2024-07-09 16:46 UTC, bynn requested changes

2024-07-09 16:46 UTC, bynn commented on thirdparty/runtime_environments.go
> +		if c.Type == "Packages" || c.Type == "Toolchains" {
lets make these a const somewhere so we're not just checking for a random string

2024-07-09 17:15 UTC, minnakt approved these changes
lgtm mod Bynn's requested changes

2024-07-09 19:02 UTC, bynn approved these changes
lgtm with 1 nit

2024-07-09 19:02 UTC, bynn commented on thirdparty/runtime_environments.go
> +	Packages   = "Packages"
nit: could we change the variable name to be bit specific 
ie `EnvTypePackage` or something like that

2024-07-09 20:36 UTC, merged