DEVPROD-5995: Add GraphQL support for githubPermissionGroupByRequester field
evergreen-ci/evergreen pull request #8067
Opened 2024-07-03 19:53 UTC by minnakt

DEVPROD-5995

### Description
Adds GraphQL support for the `githubPermissionGroupByRequester` field which was added to the `ProjectRef` in earlier work.

### Testing
- Added unit tests and GraphQL tests

2024-07-08 21:05 UTC, hadjri requested changes

2024-07-08 21:05 UTC, hadjri commented on model/project_ref.go
> +					projectRefGithubPermissionGroupByRequester: p.GitHubPermissionGroupByRequester,
Can we rename this to projectRefGithubPermissionGroupByRequesterKey to be consistent with key naming? (also same for `projectRefGitHubDynamicTokenPermissionGroups`)

2024-07-08 21:05 UTC, hadjri commented on rest/data/project_settings_test.go
> +			assert.Equal(t, pRefFromDB.GitHubPermissionGroupByRequester[evergreen.GitTagRequester], "permission-group")
Same comment about length here

2024-07-09 13:26 UTC, minnakt commented on model/project_ref_test.go
> +	require.NotNil(t, projectRef.GitHubPermissionGroupByRequester)
done also added comments (sorry I forgot them)

2024-07-09 14:32 UTC, hadjri approved these changes

2024-07-11 13:17 UTC, merged