DEVPROD-11682 Remove GlobalGitHubTokenExpansion
evergreen-ci/evergreen pull request #8347
Opened 2024-09-26 21:55 UTC by malikchaya2

DEVPROD-11682 

### Description
This is no longer needed 

### Testing
existing tests

2024-09-30 19:06 UTC, Kimchelly requested changes
* Can we remove [the oauth token parameter](https://github.com/evergreen-ci/evergreen/blob/159e1e949078e78201cb49b93cd6b653b4ca17bf/model/project.go#L1016) from the expansions since it should now be unused?
* Can we delete the `GlobalGitHubTokenExpansion` constant since it should be unused?
* Should [this doc](https://github.com/evergreen-ci/evergreen/blob/b5fa0e3a78228f51f5fbcbf354cdd920d234bc45/docs/Project-Configuration/Project-Commands.md?plain=1#L456) be updated since the expansion will no longer exist?

2024-09-30 19:06 UTC, Kimchelly commented on agent/command/git_test.go
> +	// s.comm.CreateInstallationTokenResult = mockedGitHubAppToken
Can this be removed? Or is it still needed?

2024-09-30 19:06 UTC, Kimchelly commented on agent/internal/client/base_client.go
> +func (c *baseCommunicator) CreateCachedInstallationToken(context.Context, string, string, time.Duration, *github.InstallationTokenOptions) (string, error) {
Can remove this since it's unused code.

2024-10-01 14:44 UTC, malikchaya2 commented
> * Can we remove [the oauth token parameter](https://github.com/evergreen-ci/evergreen/blob/159e1e949078e78201cb49b93cd6b653b4ca17bf/model/project.go#L1016) from the expansions since it should now be unused?
> * Can we delete the `GlobalGitHubTokenExpansion` constant since it should be unused?
> * Should [this doc](https://github.com/evergreen-ci/evergreen/blob/b5fa0e3a78228f51f5fbcbf354cdd920d234bc45/docs/Project-Configuration/Project-Commands.md?plain=1#L456) be updated since the expansion will no longer exist?

Yes, I picked these changes out of a larger change and left a few behind accidentally. Thank you!

2024-10-01 14:55 UTC, malikchaya2 commented on agent/command/git.go
>  	if appToken != "" {
I think we can assume that no errors means a token was generated. On top of that, there may be situations where things will still work without one like cloning public repos.

2024-10-02 14:08 UTC, Kimchelly approved these changes
LGTM mod remove [the now-unused `oauthToken` parameter for `PopulateExpansions`](https://github.com/evergreen-ci/evergreen/blob/75b190c63859657f5f808219e5432d891c33c973/model/project.go#L1004).

2024-10-02 14:52 UTC, merged