DEVPROD-13053 Add logs indicating token permission level
evergreen-ci/evergreen pull request #8587
Opened 2024-12-31 17:55 UTC by malikchaya2

DEVPROD-13053

### Description
It can be hard to debug if an operation is failing because the token doesn't have the correct permissions or if it's something else. This which permissions we are requesting and which permissions the token has. 

### Testing
[Tested on staging ](https://spruce.chaya-malik.evergreen-staging.devprod.mongodb.com/task/playground_ubuntu_test_generate_token_patch_e2c0245ee9dbf378e017d8564ec70b378df7adc3_6774216595c8a30007d6d142_24_12_31_16_53_08/logs?execution=0)

2025-01-03 20:35 UTC, ablack12 requested changes

2025-01-03 20:35 UTC, ablack12 commented on agent/command/github_generate_token.go
> +func permissionsToString(permissions *github.InstallationPermissions) string {
although this is a private function so doesn't require a comment, it might be nice to have one to summarize what the output looks like

2025-01-03 20:35 UTC, ablack12 commented on apimodels/agent_models.go
>  // Token is a struct which wraps a GitHub generated token.
and associated permissions?

2025-01-03 20:35 UTC, ablack12 commented on config.go
> +	AgentVersion = "2024-01-03"
2025 😭

2025-01-06 16:59 UTC, malikchaya2 commented on agent/internal/client/base_client.go
> +	type Response struct {
oh yes, thank you, good catch! This is left over from my initial draft.

2025-01-07 20:35 UTC, ablack12 approved these changes

2025-01-07 20:35 UTC, ablack12 commented on model/githubapp/github_app_auth.go
> +func (g *GithubAppAuth) CreateInstallationToken(ctx context.Context, owner, repo string, opts *github.InstallationTokenOptions) (string, *github.InstallationPermissions, error) {
Overall LGTM -- a nice improvement I think would be to change the Token struct to APIToken, and then add a Token struct to be used by these functions, as opposed to returning multiple things (and could have a tiny  BuildFromService that you could use) but up to you if you want to add that here, non blocking

2025-01-08 18:57 UTC, malikchaya2 commented on model/githubapp/github_app_auth.go
> +func (g *GithubAppAuth) CreateInstallationToken(ctx context.Context, owner, repo string, opts *github.InstallationTokenOptions) (string, *github.InstallationPermissions, error) {
I think I'll leave this as a potential future improvement so that we can merge this faster 🙏🏻

2025-01-08 19:42 UTC, merged